name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    env:
      WINEPREFIX: ${{github.workspace}}/.wine
    steps:
    - name: Install devkitPro
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get -y install build-essential wine32
        sudo chown $(whoami) "$GITHUB_WORKSPACE"
        curl -OL https://github.com/indygreg/python-build-standalone/releases/download/20230507/cpython-3.8.16+20230507-x86_64-unknown-linux-gnu-install_only.tar.gz
        tar xvf *.tar.gz
        export PYTHON38=$PWD/python/bin/python3
        curl -L https://github.com/encounter/decomp-toolkit/releases/download/v0.2.3/dtk-linux-x86_64 -o dtk
        chmod +x dtk
        export DTK=$PWD/dtk
    - uses: actions/checkout@v3
    - name: Download compilers
      run: |
        curl -L https://cdn.discordapp.com/attachments/727918646525165659/917185027656286218/GC_WII_COMPILERS.zip \
          | bsdtar -xvf- -C tools --exclude Wii
        mv tools/GC tools/mwcc_compiler
    - name: make
      run: make -j PYTHON=$PYTHON38 DTK=$DTK
